[build]
  publish = "public"
  functions = "functions"
  
 [[redirects]]
   to = "/.netlify/functions/api/"
   from="/*"
   status=200

  [functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"